version: '3'
services:
  schibsted-web:
    build:
        context: .
        dockerfile: Dockerfile.client
    ports:
    - "3000:80"
  schibsted-api:
    build:
        context: .
        dockerfile: Dockerfile.server
    ports:
    - "5000:5000"

