FROM mhart/alpine-node:11

RUN mkdir -p /usr/src/app/packages/server

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY packages/server/package.json ./packages/server/

RUN yarn install --pure-lockfile

COPY . .
RUN yarn workspace schibsted-server run build

COPY packages/server/src/fixtures ./packages/server/build/fixtures

EXPOSE 5000

CMD ["node", "./packages/server/build/index.js"]
